services:
  frontend:
    image: tomcat:jdk21-openjdk-bookworm
    ports:
      - "8080:8080"
    networks:
      - front-tier
      - back-tier
#    configs:
#      - httpd-config
    command: bash -c "apt-get update -y && apt-get install -y maven  && cd /usr/local/tomcat/ && cp -r /project/src /usr/local/tomcat/webapps/ && cp /project/pom.xml /usr/local/tomcat/webapps/ && cd /usr/local/tomcat/webapps  && mvn clean package && cp -r /usr/local/tomcat/webapps/target/test /usr/local/tomcat/webapps && rm -rf  /usr/local/tomcat/webapps/target && rm /usr/local/tomcat/webapps/pom.xml && rm -rf /usr/local/tomcat/webapps/src && /usr/local/tomcat/bin/catalina.sh run"
#    tty: true
    volumes:
      - ../project:/project


  backend:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ../ScriptSql:/home
      - ../db-data:/var/lib/postgresql/data
#      - ../db-data:/home
    networks:
      - back-tier
    environment:
      #MYSQL_USER: user
      #MYSQL_PASSWORD: mypassword
      #MYSQL_DATABASE: my_database
      #MYSQL_ROOT_PASSWORD: rootpassword
      #MARIADB_ROOT_PASSWORD: test
      POSTGRES_PASSWORD: example
      POSTGRES_DB: cv


networks:
  front-tier: {}
  back-tier: {}
