INSERT INTO `project` (`projectName`, `dateproject`, `perno`, `description`) VALUES
('Projet 4A02 : Développement d\'une application complexe', '0000-00-00', 1, 'Pour ce projet nous devions créer un jeu de type ‘shoot-em-up’(lien) en 2D, nous avons donc décidé avec notre équipe de mélanger deux univers que nous apprécions, Mario Kart et Breaking Bad donnant ainsi “Breaking Kart”. Cependant contrairement aux précédents projets que nous avons pu avoir, celui-ci demandait en plus un mode de jeu en multijoueurs, cela nous a forcé à adapter notre code pour le rendre compatible avec une architecture client-serveur pour Node.Js Ce projet nous a aussi permis d\'appliquer et d\'approfondir nos connaissances en gestion de projet, via l\'utilisation d\'outils Git (Issue, Milestone, Branch). De plus, nous avons pu mettre en application sur une partie de notre projet la programmation en TDD nous permettant ainsi de couvrir plus de code et de permettre la non-régression de ce dernier lors de nos nombreuses modifications.'),
('Projet 4A01 : Développement d\'une API REST', '0000-00-00', 1, 'Le but de ce projet etait de réaliser une API REST en Servlet en Java pour une entreprise fictive (\"PizzaLand\").\r\nCela nous a permis d\'apprendre à développer une API de manière RESTful. Cette derniere permettait a ses utilisateurs de récupérer, d\'ajouter, de modifier et de supprimer des ingrédients, des pizzas (contenant des ingrédients) et des commandes (contenant des pizzas) d\'une base de données.\r\nDe plus ce projet nous a permis d\'apprendre a utiliser et a implementer l\'utilisation de \"token\".\r\nAfin de visualiser nos interactions nous avons eu l\'occasion d\'utiliser le logiciel \"Bruno\" pour executer des requetes.'),
('Projet 301-302 : Chasse au monstre\r\n', '0000-00-00', 1, '\r\nPour ce projet nous devions créer un jeu de chasse au monstre en java en prenant en compte les différentes étapes de conception, telle que de l’analyse et le développement. Ce projet mêlait différents aspects de l\'informatique et notamment des notions de clean code via l’intégration de différents patrons de conception (MVC et Observateur-observé) mais aussi des compétences de développement Efficace en apportant plus de réflexion sur les structures de données utilisées. Ce projet nécessitait une interface graphique en JavaFx permettant aux deux joueurs de jouer. De plus nous avons dû intégrer deux “IA” afin de pouvoir jouer seul, ces “IA” devant s’adapter à une certaine architecture afin de pouvoir s’intégrer sur les jeux des autres groupes. Nous avons décidé lors de la conception du jeu de rajouter des options visuelles et audios dérivées de licences de films ou de jeux existantes permettant plus d’immersion et de faire plaisir aux utilisateurs afin qu’ils puissent trouver le visuel qui leur correspond le plus.'),
('Projet 205-206 : gestion de projet/travail d\'équipe : (2023)', '0000-00-00', 0, 'Pour ce projet nous devions créer un escape game en utilisant l’application genially. Avec mon groupe nous avons choisi pour ce jeu le thème des bases de données pour notre jeu. Ce projet mélangeait la gestion de projet via la création d’un jeu en équipe et la communication en créant une affiche pour ce dernier ainsi qu’un teaser visant à donner envie de jouer. Le but de ce projet était de nous faire travailler en équipe afin de nous montrer les différentes parties que cela engendre (réunions, utilisation de méthodes de travail plus efficaces)'),
('Projet 2.04 - exploitation d\'une BDD (2023)', '0000-00-00', 0, 'Pour ce projet nous devions importer les données des JO, et créer un modèle conceptuel de données (permettant d’organiser les données afin de faciliter les futures requêtes mais aussi d’éviter les redondances), ventiler les données afin de les répartir dans les différentes tables, et effectuer des requêtes afin d’effectuer des analyses statistiques et une analyse en anglais sur des athlètes ayant des caractéristiques extrêmes. Nous devions aussi effectuer un scénario de gestion ayant pour but final d’effectuer un compte de résultats.'),
('Projet 05-06 : Recueil des besoins / Découverte de l’environnement économique (2022)', '0000-00-00', 0, 'Pour ce projet nous devions avec mon équipe créer un site web pour une entreprise en prenant en compte les différentes étapes de conception, telles que l’analyse clients , le maquettage (via l’outil WorkPress), le développement(HTML + CSS), la communication (présentation du site). Ce projet était un projet transversal, il mêlait l’informatique via la création d’un site web vitrines (compétences en HTML et en CSS), de la gestion de projets en apportant une réflexion sur les utilisateurs du site web via la création de personnas et de questionnaires afin d’analyser les besoins des utilisateurs. Ce projet incluait aussi une part de communication via une présentation de notre site web pour les clients cette dernière s’appuyant sur une vidéo sans audio projetée servant de visuel pour appuyer notre discours.'),
('Projet 104 - Introduction aux BDD (2022)', '0000-00-00', 0, 'Pour ce projet nous devions créer une base de données sur le site ACCESS, sur un thème précis (Pour notre groupe il s’agissait de la pharmacie), tout cela prenait en compte les compétences acquises durant les cours de Base de Données via la conception d’un modèle conceptuelle de données la création de tables, de formulaire, d’états sur le logiciel ACCESS , et la création de données afin de vérifier le bon fonctionnement de notre base. Mais ce projet prenait aussi en compte une part d’économie via l’analyse du fonctionnement du type d’entreprise du sujet (pharmacie), avec ses exceptions (ALD, tiers payeurs, …)'),
('Projet 102 : Jeu ludo pédagogique (2022)\r\n', '0000-00-00', 0, 'Pour ce projet nous devions créer un jeu ludo-pédagogique (Un jeu ayant pour but d\'être utilisé dans des écoles pour apprendre/développer des notions) en java, nous avions donc décidé avec notre binôme de faire un jeu de mathématiques dans lequel 2 joueurs s’affrontent sur des séries de calculs (Addition, Soustraction, Multiplication, Division) .Pour ce projet nos enseignants jouaient le rôle de clients (professeur des écoles), le jeu devant inclure de la gestion de saisie et un historique par un fichier csv.'),
('Projet 103-203 : Installation d’une machine virtuelle (2022)', '0000-00-00', 0, 'Pour ce projet nous devions apprendre à installer une machine virtuelle et comprendre les différents paramètres de configuration afin de mieux comprendre son fonctionnement. Pour ce faire nous devions installer un système Debian 64 bits et le configurer (manuellement et automatiquement), gérer les droits des utilisateurs et installer de nouveaux logiciels tels que git (Utilisation d\'apt pour charger des logiciels depuis le miroir). De plus ce projet nous a introduit l\'outil markdown afin de pouvoir faire des rapports structurés.');
INSERT INTO period Values
(1,'BUT2'),
(0,'BUT1');
INSERT INTO skills(`Title`) Values 
('Java'),
('NodeJs'),
('Socket.io'),
('Javascript'),
('TDD'),
('Git'),
('HTML'),
('CSS'),
('Travail en Equipe'),
('Repartition des tâches'),
('Estimation du temps de travail'),
('JavaEE'),
('API REST'),
('Utilisation d\'un serveur tomcat'),
('SQL-Requêtes'),
('Analyse et conception de diagrammes UMLs'),
('Developpement Efficace'),
('Clean Code'),
('Methodes de calcul de plus court chemin'),
('JavaFx'),
('Genially'),
('Filmer et monter une vidéo'),
('Gestion d\'une équipe '),
('Commandes SQL'),
('Commandes postgreSQL d\export et d\'import des fichiers csv'),
('Création d\'un MCD'),
('Analyse statistiques'),
('Réalisation d\'un compte de résultat'),
('Anglais'),
('Base de données');